### ISSUE TITLE
Can't list commands

### ISSUE THREAD

**Issue by gitowiec** [guigrpa/docx-templates#178]
I get
```
Error: Unknown alias: *ch1
    at new InvalidCommandError (node_modules/docx-templates/lib/errors.js:42:28)
    at Object.getCommand (node_modules/docx-templates/lib/processTemplate.js:563:19)
    at Object.<anonymous> (node_modules/docx-templates/lib/main.js:313:57)
    at step (node_modules/docx-templates/lib/main.js:33:23)
    at Object.next (node_modules/docx-templates/lib/main.js:14:53)
    at /home/user/workspace/fakturuj.to/packages/web-server/node_modules/docx-templates/lib/main.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (node_modules/docx-templates/lib/main.js:4:12)
    at /home/user/workspace/fakturuj.to/packages/web-server/node_modules/docx-templates/lib/main.js:310:135
    at /home/user/workspace/fakturuj.to/packages/web-server/node_modules/docx-templates/lib/processTemplate.js:401:38
    at step (node_modules/docx-templates/lib/processTemplate.js:33:23)
    at Object.next (node_modules/docx-templates/lib/processTemplate.js:14:53)
    at /home/user/workspace/fakturuj.to/packages/web-server/node_modules/docx-templates/lib/processTemplate.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (node_modules/docx-templates/lib/processTemplate.js:4:12)
    at processText (node_modules/docx-templates/lib/processTemplate.js:370:66)
    at Object.<anonymous> (node_modules/docx-templates/lib/processTemplate.js:325:42)
    at step (node_modules/docx-templates/lib/processTemplate.js:33:23)
    at Object.next (node_modules/docx-templates/lib/processTemplate.js:14:53)
    at fulfilled (node_modules/docx-templates/lib/processTemplate.js:5:58)
```

Here is how my Word template looks:

![image](https://user-images.githubusercontent.com/1553195/102611682-b328dc80-412f-11eb-8ee4-e3f3ba5644f6.png)

**Comment by jjhbw** [comment]
Interesting, can you share your template? Or at least a minimal docx file I can repro this with.

**Comment by gitowiec** [comment]
Here is my template, please debug it

[Prawne-oswiadczenie-PDOP-VAT.docx](https://github.com/guigrpa/docx-templates/files/5715532/Prawne-oswiadczenie-PDOP-VAT.docx)

**Comment by jjhbw** [comment]
Your template seems correct. Its probably an issue with listCommands not
recognizing ALIAS referencing commands (*).

**Comment by gitowiec** [comment]
I found another issue, I thought this module is production ready but I have to ditch it, because it is plenty of bugs. I need to find reliable solutions and stop debugging someones code :/

**Comment by jjhbw** [comment]
I would appreciate it if you could report that bug. Note that you're of course free to ditch this library, thats the beauty of open source.
