### ISSUE TITLE
Heroku error at http://swapi.apis.guru

### ISSUE THREAD

**Issue by jcalfee** [guigrpa/docx-templates#254]
```bash
docx-templates/examples/example-node$ npm start

> example-node@3.1.0 start /home/james/dev/inpower/docx-templates/examples/example-node
> node . swapi-simple.docx output.docx

FetchError: invalid json response body at http://swapi.apis.guru reason: Unexpected token < in JSON at position 0
    at /home/james/dev/inpower/docx-templates/examples/example-node/node_modules/node-fetch/lib/body.js:48:31
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  type: 'invalid-json'
}
```
See http://swapi.apis.guru

**Comment by jjhbw** [comment]
Thanks for pointing this out! We don't maintain this API. I think we should take the opportunity to remove this remote dependency from our example application.
