### ISSUE TITLE
The project reports an error in Vue.

### ISSUE THREAD

**Issue by fazzzzzzz** [guigrpa/docx-templates#289]
Environment: Browser, Vue3, Vite

When I add row `import createReport from 'docx-templates'`. Even if I do nothing, the webpage will report error.
web console:
```
TypeError: Cannot read properties of undefined (reading 'prototype')
    at sax.js:222:46
    at sax.js:1565:2
    at sax.js:1565:60
```
It seems that there is a problem with the library `"sax": "1.2.4"`.
sax.js:222: 
```
  SAXStream.prototype = Object.create(Stream.prototype, {
    constructor: {
      value: SAXStream
    }
  })
```
`Stream.prototype` undefined

**Comment by fazzzzzzz** [comment]
npm seems to be normal, yarn is a problem

**Comment by fazzzzzzz** [comment]
CodeSandbox : [this](https://codesandbox.io/p/sandbox/recursing-hamilton-y1qdf0?file=%2Fsrc%2Fmain.js&selection=%5B%7B%22endColumn%22%3A42%2C%22endLineNumber%22%3A4%2C%22startColumn%22%3A42%2C%22startLineNumber%22%3A4%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl8oq844n000clqd98ondacto%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fpackage.json%2522%252C%2522%252Fsrc%252Fmain.js%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clbjsydiw000u3t6g1vtf9ld3%2522%253A%257B%2522key%2522%253A%2522clbjsydiw000u3t6g1vtf9ld3%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clbjt0k5y015y7rd9htleevf8%2522%252C%2522key%2522%253A%2522clbjt0jw400qo3t6ge1zglyah%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522clbjt5jwu01if3t6gz7vn2kt7%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clbjt1cz800wa3t6gy1yrwze0%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clbjsydiw000u3t6g1vtf9ld3%2522%252C%2522spacesOrder%2522%253A%255B%2522clbjsydiw000u3t6g1vtf9ld3%2522%255D%257D)

**Comment by fazzzzzzz** [comment]
I solved this problem.

shell:
```
yarn add stream-browserify
```

vite.config.js
```
export default defineConfig(() => {
    return {
        plugins: [
            vue()
        ],
        resolve: {
            alias: {
                // add this
                'stream': 'stream-browserify'
            }
        },
        
    }
})
```
