### ISSUE TITLE
Error whit lib babel-polyfill

### ISSUE THREAD

**Issue by JonathanLSignot** [guigrpa/docx-templates#7]
Exception has occurred: Error
Error: Cannot find module 'babel-polyfill'
`include-all` attempted to `require(c:\Users\jonat\Documents\signot\backend\api\services\word.js)`, but an error occurred:: 
Details:Error: Cannot find module 'babel-polyfill'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\Users\jonat\Documents\signot\backend\node_modules\docx-templates\lib\main.js:7:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\Users\jonat\Documents\signot\backend\node_modules\docx-templates\lib\index.js:3:37)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\Users\jonat\Documents\signot\backend\api\services\word.js:8:22)
    at Module._compile (module.js:570:32)

I hab to add `"babel-polyfill": "6.23.0",` in package.json

**Comment by guigrpa** [comment]
I see. My bad!

**Comment by guigrpa** [comment]
Could you please check out v2.2.2? It should solve the problem.

Please make sure you use the new API option `replaceImagesBase64` (previously `base64`).
