### ISSUE TITLE
Cannot start the example-webpack locally

### ISSUE THREAD

**Issue by nmummau** [guigrpa/docx-templates#89]
I'm on Ubuntu 18.04.3 LTS

I've cloned the repository and am trying to run the example-webpack locally. 
`yarn install && yarn run start`
Gets me this error:
```
yarn run v1.17.3
$ yarn webpack --mode production
$ webpack --config ./webpackConfig.js --color --progress --display-chunks --mode production
/home/nmummau/Code/docx-templates/node_modules/webpack-cli/bin/config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/home/nmummau/Code/docx-templates/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at /home/nmummau/Code/docx-templates/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (/home/nmummau/Code/docx-templates/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by weidtn** [comment]
`"webpack-cli": "^3.1.1"`

in package.json

**Comment by jjhbw** [comment]
Thanks @weidtn ! That solves the problem. I've updated the example code to reflect this. Seems to be an issue in the Webpack ecosystem.
